window.SPACE_REGISTRY_LISTINGS = [
  {
    "id": "registry-1-dhanmondi-road-15",
    "registryNo": 1,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Dhanmondi",
    "location": "Dhanmondi, Road-15",
    "price": 27000,
    "units": "200 sqft / Ground floor",
    "sizeSqft": 200,
    "sizeRange": "Under 300 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "016 7466 5055",
    "contactName": "Unknown",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/v8qkizmn2xwsso8X6?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-4C3zW4qujoJ5S8Z6auyCYhaqvcru6WI?usp=sharing",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "18 month",
    "ratePerSqft": 135.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Dhanmondi, Road-15. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-2-dhanmondi-road-19",
    "registryNo": 2,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Dhanmondi",
    "location": "Dhanmondi, Road-19",
    "price": 140000,
    "units": "450 sqft / Ground floor",
    "sizeSqft": 450,
    "sizeRange": "300-799 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 1107 8080",
    "contactName": "Unknown",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/uNbFej1nXPuqSmsm8?g_st=iw.",
    "propertyLink": "https://drive.google.com/drive/folders/1-5NlYQMemsGy4WbrwTc9OXTqSnl9rFVJ",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "18 month",
    "ratePerSqft": 311.11,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Dhanmondi, Road-19. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-3-dhanmondi-road-5-a",
    "registryNo": 3,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Dhanmondi",
    "location": "Dhanmondi, Road-5/A",
    "price": 130000,
    "units": "1200 sqft / 3rd floor",
    "sizeSqft": 1200,
    "sizeRange": "800-1,499 sqft",
    "floor": "3rd",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 1182 0001",
    "contactName": "Unknown",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/M6FGMjSueBU1jNfU6?g_st=iw.",
    "propertyLink": "https://drive.google.com/drive/folders/1-B9Le7wvGN-_jdBsXwSCMhsh7HwdMlLv",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "12 month",
    "ratePerSqft": 108.33,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Dhanmondi, Road-5/A. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-4-wari-tipusultan-road",
    "registryNo": 4,
    "brand": "Active",
    "status": "Under Review",
    "title": "Mixed Use space in Wari",
    "location": "Wari, Tipusultan Road",
    "price": 157000,
    "units": "2250 sqft / 2nd floor",
    "sizeSqft": 2250,
    "sizeRange": "1,500-2,499 sqft",
    "floor": "2nd",
    "propertyType": "Residential (modified)",
    "intendedUse": "Mixed Use",
    "contact": "017 9984 2203",
    "contactName": "Unknown",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/CaTBfy5AiqYpbskz7?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-D84GwD5NJt1eP-CJODNXimAVemmiYOJ",
    "photoUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "deposit": "6 month",
    "ratePerSqft": 69.78,
    "utilities": {
      "gas": "LPG",
      "electric": "Res",
      "water": "Res"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Mixed Use Residential (modified) space at Wari, Tipusultan Road. Utilities: gas LPG, electric Res, water Res. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-5-wari-nobab-street",
    "registryNo": 5,
    "brand": "Active",
    "status": "Under Review",
    "title": "Mixed Use space in Wari",
    "location": "Wari, Nobab Street",
    "price": 200000,
    "units": "1350 sqft / Ground floor",
    "sizeSqft": 1350,
    "sizeRange": "800-1,499 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Mixed Use",
    "contact": "016 8417 2618",
    "contactName": "Unknown",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/zb1Vt8Fk3NaCD2BBA?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-FxvBwCLrj5w1E7tQFIN_A_VHH0ol7PY",
    "photoUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "deposit": "25 month",
    "ratePerSqft": 148.15,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Mixed Use Commercial space at Wari, Nobab Street. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-6-uttara-sector-1-road-2-house",
    "registryNo": 6,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Uttara",
    "location": "Uttara, sector-1, Road-2, House-2",
    "price": 200000,
    "units": "2000 sqft / 3rd floor",
    "sizeSqft": 2000,
    "sizeRange": "1,500-2,499 sqft",
    "floor": "3rd",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 1154 7145",
    "contactName": "Unknown",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/wR6JnuD7L9JbGcGM6?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-Y9WJInmIywWNl6bfr7pEzI-zNN-LY8W",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "9 month",
    "ratePerSqft": 100.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Uttara, sector-1, Road-2, House-2. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-7-bashundhara-apolo-road",
    "registryNo": 7,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Bashundhara",
    "location": "Bashundhara, Apolo Road",
    "price": 40000,
    "units": "500 sqft / 1st floor",
    "sizeSqft": 500,
    "sizeRange": "300-799 sqft",
    "floor": "1st",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 1149 0054",
    "contactName": "Unknown",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/ZGqPbCDzZrNNbuNr7?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-Z8VfHh4dfmWuxNpg1BofMIVtU_-fIk7",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "10 month",
    "ratePerSqft": 80.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Bashundhara, Apolo Road. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-8-bashundhara-apolo-road-j-mar",
    "registryNo": 8,
    "brand": "Active",
    "status": "Under Review",
    "title": "Warehouse space in Bashundhara",
    "location": "Bashundhara, Apolo Road, J-mart",
    "price": 80000,
    "units": "1200 sqft / Ground floor",
    "sizeSqft": 1200,
    "sizeRange": "800-1,499 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Warehouse",
    "contact": "015 1874 8614",
    "contactName": "Unknown",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/SXTpbbZ3e4kh21Ae9?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-_o97qtmGz4Y6OMlz7OFjic2h2qCepAw",
    "photoUrl": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    "deposit": "3 month",
    "ratePerSqft": 66.67,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "No"
    },
    "description": "Warehouse Commercial space at Bashundhara, Apolo Road, J-mart. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust No."
  },
  {
    "id": "registry-9-baridhara-j-block-road-8-hou",
    "registryNo": 9,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Baridhara",
    "location": "Baridhara, J-block, Road-8, House-8",
    "price": 16000,
    "units": "100 sqft / Ground floor",
    "sizeSqft": 100,
    "sizeRange": "Under 300 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "019 1174 5343",
    "contactName": "Unknown",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/TNhSBJQ4GcXFnNqj9?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-Q4eCAAs-FwZriNt0iLQ9yQqZgsCcGKH",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "32 month",
    "ratePerSqft": 160.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "No"
    },
    "description": "Retail Commercial space at Baridhara, J-block, Road-8, House-8. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust No."
  },
  {
    "id": "registry-10-baridhara-j-block-road-8",
    "registryNo": 10,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Baridhara",
    "location": "Baridhara, J-block, Road-8",
    "price": 30000,
    "units": "139 sqft / Ground floor",
    "sizeSqft": 139,
    "sizeRange": "Under 300 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 4447 1354 ",
    "contactName": "Unknown",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/1SVQcPrE6vyf5FXs9?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-cVUwt8twN92vj7_xsv4LO-rpDZwORzS",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "10 month",
    "ratePerSqft": 215.83,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "No"
    },
    "description": "Retail Commercial space at Baridhara, J-block, Road-8. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust No."
  },
  {
    "id": "registry-11-baridhara-j-block-beside-roa",
    "registryNo": 11,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Baridhara",
    "location": "Baridhara, J-block, Beside Road-8",
    "price": 30000,
    "units": "300 sqft / Ground floor",
    "sizeSqft": 300,
    "sizeRange": "300-799 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 1505 3223",
    "contactName": "Unknown",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/CGdjSxgRfBdbXJw39?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-f1r0mSB5JJt9hIEnmw2KutsZMQSC_iJ",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "10 month",
    "ratePerSqft": 100.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "No"
    },
    "description": "Retail Commercial space at Baridhara, J-block, Beside Road-8. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust No."
  },
  {
    "id": "registry-12-merul-badda-beside-brac-univ",
    "registryNo": 12,
    "brand": "Active",
    "status": "Under Review",
    "title": "Mixed Use space in Merul Badda",
    "location": "Merul Badda, Beside Brac University",
    "price": 180000,
    "units": "2400 sqft / 3rd floor",
    "sizeSqft": 2400,
    "sizeRange": "1,500-2,499 sqft",
    "floor": "3rd",
    "propertyType": "Commercial",
    "intendedUse": "Mixed Use",
    "contact": "017 1265 7210",
    "contactName": "Mozammel Haque",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/LKejY4dccq7sxezL9?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-qvFPNCopxy4x4kiU9vLHZkOeJLHD-DN",
    "photoUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "deposit": "9 month",
    "ratePerSqft": 75.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Mixed Use Commercial space at Merul Badda, Beside Brac University. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-13-banusree-block-b-avenue-2",
    "registryNo": 13,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Banusree",
    "location": "Banusree, Block-B, Avenue-2",
    "price": 45000,
    "units": "350 sqft / Ground floor",
    "sizeSqft": 350,
    "sizeRange": "300-799 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 1196 3936",
    "contactName": "Unknown",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/yQzweKhjfdw5VXd69?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/14O_wHJ-D4aVlTJI9oELdesZOc9MHWdqR",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "32 month",
    "ratePerSqft": 128.57,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Banusree, Block-B, Avenue-2. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-14-banani-block-e-road-12-house",
    "registryNo": 14,
    "brand": "Active",
    "status": "Under Review",
    "title": "Mixed Use space in Banani",
    "location": "Banani, Block-E, Road-12, House-134",
    "price": 200000,
    "units": "700 sqft / Ground floor",
    "sizeSqft": 700,
    "sizeRange": "300-799 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Mixed Use",
    "contact": "017 1033 5631",
    "contactName": "Unknown",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/yQzweKhjfdw5VXd69?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-0C3y0Z0-bwelERoXcmjTxbDWMROYW3M",
    "photoUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "deposit": "6 month",
    "ratePerSqft": 285.71,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "No"
    },
    "description": "Mixed Use Commercial space at Banani, Block-E, Road-12, House-134. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust No."
  },
  {
    "id": "registry-15-dhanmondi-road-27",
    "registryNo": 15,
    "brand": "Active",
    "status": "Under Review",
    "title": "Mixed Use space in Dhanmondi",
    "location": "Dhanmondi, Road-27",
    "price": 900000,
    "units": "2256 sqft / Ground floor",
    "sizeSqft": 2256,
    "sizeRange": "1,500-2,499 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Mixed Use",
    "contact": "017 3297 9297 ",
    "contactName": "Unknown",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/NLFStuxHkkKjpLUY8?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-12CBnZuNy8S230STaxBFoJz9rU-J_T0",
    "photoUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "deposit": "12 month",
    "ratePerSqft": 398.94,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Mixed Use Commercial space at Dhanmondi, Road-27. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-16-dhanmondi-road-27-baside-ibn",
    "registryNo": 16,
    "brand": "Active",
    "status": "Under Review",
    "title": "Mixed Use space in Dhanmondi",
    "location": "Dhanmondi, Road-27, Baside Ibnesina Hospital(1)",
    "price": 700000,
    "units": "1400 sqft / 1st floor",
    "sizeSqft": 1400,
    "sizeRange": "800-1,499 sqft",
    "floor": "1st",
    "propertyType": "Commercial",
    "intendedUse": "Mixed Use",
    "contact": "017 8923 1251",
    "contactName": "Unknown",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/NLFStuxHkkKjpLUY8?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-2Hw_aKHGz8hZacuaYamkgGh4xmowKeD",
    "photoUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "deposit": "6 month",
    "ratePerSqft": 500.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Mixed Use Commercial space at Dhanmondi, Road-27, Baside Ibnesina Hospital(1). Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-17-merul-badda",
    "registryNo": 17,
    "brand": "Active",
    "status": "Under Review",
    "title": "Mixed Use space in Merul Badda ",
    "location": "Merul Badda ",
    "price": 280000,
    "units": "3000 sqft / 4th floor",
    "sizeSqft": 3000,
    "sizeRange": "2,500+ sqft",
    "floor": "4th",
    "propertyType": "Commercial",
    "intendedUse": "Mixed Use",
    "contact": "017 9026 7167",
    "contactName": "Shojol",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/sJ1YtkDm8VmTGZye8?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-F9ZBTn36_YD0plMHqX-JvgZHf0-eAXF",
    "photoUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "deposit": "6 month",
    "ratePerSqft": 93.33,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Mixed Use Commercial space at Merul Badda . Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-18-aftab-nogor-beside-east-west",
    "registryNo": 18,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Aftab Nogor",
    "location": "Aftab Nogor, Beside East West University",
    "price": 40000,
    "units": "500 sqft / Ground floor",
    "sizeSqft": 500,
    "sizeRange": "300-799 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "019 1957 1227",
    "contactName": "Unknown",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/1fNJJa3ZE8NPbQt69?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-KmUNrcjWXdjzceWa2dtKosm_SzUtHMA",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "30 month",
    "ratePerSqft": 80.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Aftab Nogor, Beside East West University. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-19-aftab-nogor-live-fresh",
    "registryNo": 19,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Aftab Nogor",
    "location": "Aftab Nogor, Live Fresh",
    "price": 92000,
    "units": "715 sqft / Ground floor",
    "sizeSqft": 715,
    "sizeRange": "300-799 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "018 6041 8821",
    "contactName": "Unknown",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/FXYiUCieZ3Q5aXYq9?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-MZOVExuVjE_Z2tFFlM7EzrYNhayMplG",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "12 month",
    "ratePerSqft": 128.67,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Aftab Nogor, Live Fresh. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-20-dhanmondi-road-27-herfy",
    "registryNo": 20,
    "brand": "Active",
    "status": "Under Review",
    "title": "Mixed Use space in Dhanmondi",
    "location": "Dhanmondi, Road-27, Herfy",
    "price": 420000,
    "units": "2800 sqft / 1st floor",
    "sizeSqft": 2800,
    "sizeRange": "2,500+ sqft",
    "floor": "1st",
    "propertyType": "Commercial",
    "intendedUse": "Mixed Use",
    "contact": "017 0999 1014",
    "contactName": "Unknown",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/sntkQn5JJQPPaDoYA",
    "propertyLink": "https://drive.google.com/drive/folders/1-MV1oT9MKismdlNF2S59NULKrARAFZ3u",
    "photoUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "deposit": "6 month",
    "ratePerSqft": 150.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Mixed Use Commercial space at Dhanmondi, Road-27, Herfy. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-21-opposite-of-jigatola-post-of",
    "registryNo": 21,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Opposite of Jigatola post Office(1)",
    "location": "Opposite of Jigatola post Office(1)",
    "price": 30000,
    "units": "160 sqft / Ground floor",
    "sizeSqft": 160,
    "sizeRange": "Under 300 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "016 7407 3348",
    "contactName": "Mizan",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/rfbNA9aj2FmVzzBY8?g_st=aw",
    "propertyLink": "https://drive.google.com/drive/folders/1Zqx5ERjiBHwchww5xKXBjT_wfgTNqtS2",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "17 month",
    "ratePerSqft": 187.5,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Opposite of Jigatola post Office(1). Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-22-sadarghat-gaptoli-road-besid",
    "registryNo": 22,
    "brand": "Active",
    "status": "Under Review",
    "title": "Mixed Use space in Sadarghat-Gaptoli road",
    "location": "Sadarghat-Gaptoli road, Beside sikhdar medical",
    "price": 38000,
    "units": "2600 sqft / Ground floor",
    "sizeSqft": 2600,
    "sizeRange": "2,500+ sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Mixed Use",
    "contact": "017 0420 5455",
    "contactName": "Noman",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/JFwD5qCefgmB3M9K6",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgBvLjVGVPwuQ5lDvHsSc36IAVH6o0un8egvRwmGI1afyns?e=0whosj",
    "photoUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "deposit": "6 month",
    "ratePerSqft": 14.62,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Mixed Use Commercial space at Sadarghat-Gaptoli road, Beside sikhdar medical. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-23-rayer-bazar",
    "registryNo": 23,
    "brand": "Haven",
    "status": "Active",
    "title": "Other space in Rayer Bazar",
    "location": "Rayer Bazar",
    "price": 17000,
    "units": "740 sqft / Ground floor",
    "sizeSqft": 740,
    "sizeRange": "300-799 sqft",
    "floor": "Ground",
    "propertyType": "Residential (modified)",
    "intendedUse": "Other",
    "contact": "016 1904 0000",
    "contactName": "Maksudul Islam",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/QwFSagUrLVjdEgnk9?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgCld5d6AiExSa4JsNbw1YA5AUkBO4cxcvC1iAtBmiBfqRw?e=NybiWs",
    "photoUrl": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80",
    "deposit": "2 month",
    "ratePerSqft": 22.97,
    "utilities": {
      "gas": "LPG",
      "electric": "Res",
      "water": "Res"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Other Residential (modified) space at Rayer Bazar. Utilities: gas LPG, electric Res, water Res. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-24-notun-bazar-madani-avenue",
    "registryNo": 24,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Notun Bazar",
    "location": "Notun Bazar, Madani Avenue ",
    "price": 100000,
    "units": "3500 sqft / Ground floor",
    "sizeSqft": 3500,
    "sizeRange": "2,500+ sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "016 0262 5832",
    "contactName": "Aftaruzzaman Babu",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/ZK6faSH74BQLvgmg6?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgDEury2h1BJQbJO_yDAmY5tAfE1fm4zDTHTyb33HyUeBEQ?e=lRiBvH",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "10 month",
    "ratePerSqft": 28.57,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Notun Bazar, Madani Avenue . Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-25-opposite-of-jigatola-post-of",
    "registryNo": 25,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Opposite of Jigatola post Office(2)",
    "location": "Opposite of Jigatola post Office(2)",
    "price": 30000,
    "units": "180 sqft / Ground floor",
    "sizeSqft": 180,
    "sizeRange": "Under 300 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "016 7407 3348",
    "contactName": "Mizan",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/rfbNA9aj2FmVzzBY8?g_st=aw",
    "propertyLink": "https://drive.google.com/drive/folders/1Zqx5ERjiBHwchww5xKXBjT_wfgTNqtS2",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "17 month",
    "ratePerSqft": 166.67,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Opposite of Jigatola post Office(2). Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-26-opposite-of-jigatola-post-of",
    "registryNo": 26,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Opposite of Jigatola post Office(3)",
    "location": "Opposite of Jigatola post Office(3)",
    "price": 30000,
    "units": "180 sqft / Ground floor",
    "sizeSqft": 180,
    "sizeRange": "Under 300 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "016 7407 3348",
    "contactName": "Mizan",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/rfbNA9aj2FmVzzBY8?g_st=aw",
    "propertyLink": "https://drive.google.com/drive/folders/1Zqx5ERjiBHwchww5xKXBjT_wfgTNqtS2",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "17 month",
    "ratePerSqft": 166.67,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Opposite of Jigatola post Office(3). Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-27-dhanmondi-road-27-beside-ibn",
    "registryNo": 27,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Dhanmondi",
    "location": "Dhanmondi, Road-27, Beside ibnesina hospital(2)",
    "price": 500000,
    "units": "1000 sqft / 1st floor",
    "sizeSqft": 1000,
    "sizeRange": "800-1,499 sqft",
    "floor": "1st",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 8923 1251",
    "contactName": "Unknown",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/NLFStuxHkkKjpLUY8?g_st=iw",
    "propertyLink": "https://drive.google.com/drive/folders/1-2Hw_aKHGz8hZacuaYamkgGh4xmowKeD",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "6 month",
    "ratePerSqft": 500.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Dhanmondi, Road-27, Beside ibnesina hospital(2). Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-28-notun-bazar-madani-avenue-2",
    "registryNo": 28,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Notun Bazar",
    "location": "Notun Bazar, Madani Avenue (2)",
    "price": 50000,
    "units": "1200 sqft / Ground floor",
    "sizeSqft": 1200,
    "sizeRange": "800-1,499 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 1830 2241",
    "contactName": "Bellal",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/fEtHNVQDT72T3YSC8?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgClyWdHpccpRLQxaQD60bTxAZ6A_BtqItt2CYO3gYvof5I?e=BGK7Ip",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "10 month",
    "ratePerSqft": 41.67,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Notun Bazar, Madani Avenue (2). Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-29-mirpur-sony-square",
    "registryNo": 29,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Mirpur",
    "location": "Mirpur, Sony square",
    "price": 100000,
    "units": "1000 sqft / 1st floor",
    "sizeSqft": 1000,
    "sizeRange": "800-1,499 sqft",
    "floor": "1st",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "016 0262 5832",
    "contactName": "Babu",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/RUoAPBZUY7Aov6JN6?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgANh_GvlkgYRoNtZBcJ4F-KAXj9r3rwrCcKOIeNqv-UO6E?e=rvJduZ",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "25 month",
    "ratePerSqft": 100.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Mirpur, Sony square. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-30-notun-bazar-solmait-cristain",
    "registryNo": 30,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Notun Bazar",
    "location": "Notun Bazar, Solmait, Cristain Building",
    "price": 30000,
    "units": "850 sqft / Ground floor",
    "sizeSqft": 850,
    "sizeRange": "800-1,499 sqft",
    "floor": "Ground",
    "propertyType": "Residential (modified)",
    "intendedUse": "Retail",
    "contact": "017 1880 9118",
    "contactName": "Paul",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/57DM8ox3BVhtnMLs5?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgDysKy0jdvVRKKCjK9LoRqnAYSmO8cDgSSHg-hKEyhSL3o?e=bp9AXm",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "10 month",
    "ratePerSqft": 35.29,
    "utilities": {
      "gas": "LPG",
      "electric": "Res",
      "water": "Res"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Residential (modified) space at Notun Bazar, Solmait, Cristain Building. Utilities: gas LPG, electric Res, water Res. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-31-sobhanbag-opposite-of-metro-",
    "registryNo": 31,
    "brand": "Active",
    "status": "Under Review",
    "title": "Mixed Use space in Sobhanbag",
    "location": "Sobhanbag, opposite of metro shopping mall",
    "price": 120000,
    "units": "900 sqft / 1st floor",
    "sizeSqft": 900,
    "sizeRange": "800-1,499 sqft",
    "floor": "1st",
    "propertyType": "Commercial",
    "intendedUse": "Mixed Use",
    "contact": "018 4415 2884",
    "contactName": "Zayen Newaz",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/Zn5MfzT7aZhrRELi9?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgBJE7-rHkc2SrD5K65qUD4FAbdbXAwLmyjpAWYatQDkpus?e=KIrqd0",
    "photoUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "deposit": "6 month",
    "ratePerSqft": 133.33,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Mixed Use Commercial space at Sobhanbag, opposite of metro shopping mall. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-32-shobhanbag-beside-of-metro-s",
    "registryNo": 32,
    "brand": "Active",
    "status": "Under Review",
    "title": "Mixed Use space in Shobhanbag",
    "location": "Shobhanbag, Beside of metro shopping mall",
    "price": 120000,
    "units": "1600 sqft / 1st floor",
    "sizeSqft": 1600,
    "sizeRange": "1,500-2,499 sqft",
    "floor": "1st",
    "propertyType": "Commercial",
    "intendedUse": "Mixed Use",
    "contact": "018 4415 2884",
    "contactName": "Zayen Newaz",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/cH1cJuTP73ij61Xb9?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgDRM2VM1a_pTok5q4veJR_QAcLwRRMnnydfMVImR5IekK8?e=1fvVUc",
    "photoUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "deposit": "21 month",
    "ratePerSqft": 75.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Mixed Use Commercial space at Shobhanbag, Beside of metro shopping mall. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-33-shobhanbag-beside-of-metro-s",
    "registryNo": 33,
    "brand": "Active",
    "status": "Under Review",
    "title": "Mixed Use space in Shobhanbag",
    "location": "Shobhanbag, Beside of metro shopping mall",
    "price": 120000,
    "units": "1600 sqft / 2nd floor",
    "sizeSqft": 1600,
    "sizeRange": "1,500-2,499 sqft",
    "floor": "2nd",
    "propertyType": "Commercial",
    "intendedUse": "Mixed Use",
    "contact": "018 4415 2884 ",
    "contactName": "Zayen Newaz",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/cH1cJuTP73ij61Xb9?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgDRM2VM1a_pTok5q4veJR_QAcLwRRMnnydfMVImR5IekK8?e=1fvVUc",
    "photoUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "deposit": "13 month",
    "ratePerSqft": 75.0,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Mixed Use Commercial space at Shobhanbag, Beside of metro shopping mall. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-34-mohammadpur-ghatar-chor",
    "registryNo": 34,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Mohammadpur",
    "location": "Mohammadpur, Ghatar Chor",
    "price": 46000,
    "units": "800 sqft / Ground floor",
    "sizeSqft": 800,
    "sizeRange": "800-1,499 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 2687 9717",
    "contactName": "Mumin Khan",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/nzHN22NDvN6Wf4fP8?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgCnXmA1dWfpT5OhNzel9guhAUNxWK1U4yvNCe2eCQANAxI?e=zmBcUS",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "6 month",
    "ratePerSqft": 57.5,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Mohammadpur, Ghatar Chor. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-35-mohammadpur-ghatar-chor",
    "registryNo": 35,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Mohammadpur",
    "location": "Mohammadpur, Ghatar Chor",
    "price": 50000,
    "units": "2400 sqft / 1st floor",
    "sizeSqft": 2400,
    "sizeRange": "1,500-2,499 sqft",
    "floor": "1st",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 2687 9717",
    "contactName": "Mumin Khan",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/nzHN22NDvN6Wf4fP8?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgCnXmA1dWfpT5OhNzel9guhAUNxWK1U4yvNCe2eCQANAxI?e=zmBcUS",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "6 month",
    "ratePerSqft": 20.83,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Mohammadpur, Ghatar Chor. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-36-mohammadpur-ghatar-chor",
    "registryNo": 36,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Mohammadpur",
    "location": "Mohammadpur, Ghatar Chor",
    "price": 50000,
    "units": "2400 sqft / 1st floor",
    "sizeSqft": 2400,
    "sizeRange": "1,500-2,499 sqft",
    "floor": "1st",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 2687 9717",
    "contactName": "Mumin Khan",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/nzHN22NDvN6Wf4fP8?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgAGKz-xVHMrRa-EqbVSRzrGAc9Cwoz_i2jvz92EwsjDCoI?e=m2Ui4C",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "6 month",
    "ratePerSqft": 20.83,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Mohammadpur, Ghatar Chor. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-37-mohammadpur-ghatar-chor",
    "registryNo": 37,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Mohammadpur",
    "location": "Mohammadpur, Ghatar Chor",
    "price": 50000,
    "units": "2350 sqft / 1st floor",
    "sizeSqft": 2350,
    "sizeRange": "1,500-2,499 sqft",
    "floor": "1st",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "017 2687 9717",
    "contactName": "Mumin Khan",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/nzHN22NDvN6Wf4fP8?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgAGKz-xVHMrRa-EqbVSRzrGAc9Cwoz_i2jvz92EwsjDCoI?e=m2Ui4C",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "6 month",
    "ratePerSqft": 21.28,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Mohammadpur, Ghatar Chor. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-38-mohammadpur-nurzahan-road",
    "registryNo": 38,
    "brand": "Active",
    "status": "Under Review",
    "title": "Retail space in Mohammadpur",
    "location": "Mohammadpur, Nurzahan Road",
    "price": 65000,
    "units": "350 sqft / Ground floor",
    "sizeSqft": 350,
    "sizeRange": "300-799 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "018 4415 2884",
    "contactName": "Zayen Newaz",
    "identity": "Broker",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/kwwYUNsBkPcneVnt6?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgBCPll2RqE8RqfT9TrytreaAaXrl11NdBkaVTsYZPecNmQ?e=tpuZ2T",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "8 month",
    "ratePerSqft": 185.71,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Mohammadpur, Nurzahan Road. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  },
  {
    "id": "registry-39-gulshan-badda-link-road-1",
    "registryNo": 39,
    "brand": "Haven",
    "status": "Under Review",
    "title": "Storage space in Gulshan-Badda Link Road 1",
    "location": "Gulshan-Badda Link Road 1",
    "price": 25000,
    "units": "400 sqft / Ground floor",
    "sizeSqft": 400,
    "sizeRange": "300-799 sqft",
    "floor": "Ground",
    "propertyType": "Residential (modified)",
    "intendedUse": "Storage",
    "contact": "016 3272 8434",
    "contactName": "Rahim",
    "identity": "Caretaker ",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/SiFhUvBqSLRrpb2A7?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgB7o38f5Iy9RrtEtjwTKgRsAULfzph5RzlVZLZ_oM3sC9c?e=9dOOc4",
    "photoUrl": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80",
    "deposit": "4 month",
    "ratePerSqft": 62.5,
    "utilities": {
      "gas": "LPG",
      "electric": "Res",
      "water": "Res"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "No"
    },
    "description": "Storage Residential (modified) space at Gulshan-Badda Link Road 1. Utilities: gas LPG, electric Res, water Res. Access: 24/7 Yes, truck Yes, exhaust No."
  },
  {
    "id": "registry-40-gulshan-badda-link-road-2",
    "registryNo": 40,
    "brand": "Haven",
    "status": "Under Review",
    "title": "Storage space in Gulshan-Badda Link Road 2",
    "location": "Gulshan-Badda Link Road 2",
    "price": 50000,
    "units": "1300 sqft / 1st floor",
    "sizeSqft": 1300,
    "sizeRange": "800-1,499 sqft",
    "floor": "1st",
    "propertyType": "Residential (modified)",
    "intendedUse": "Storage",
    "contact": "013 4534 7445",
    "contactName": "Salman",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/MuWKk6auNRrhGGHH7?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgDHaWmZCqbmSqkbK3SW-MZ6ARBkTNWj-ogpJt4ZvDOgr1c?e=CSDX1Z",
    "photoUrl": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80",
    "deposit": "3 month",
    "ratePerSqft": 38.46,
    "utilities": {
      "gas": "LPG",
      "electric": "Res",
      "water": "Res"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "No"
    },
    "description": "Storage Residential (modified) space at Gulshan-Badda Link Road 2. Utilities: gas LPG, electric Res, water Res. Access: 24/7 Yes, truck Yes, exhaust No."
  },
  {
    "id": "registry-41-gulshan-badda-link-road-3",
    "registryNo": 41,
    "brand": "Haven",
    "status": "Active",
    "title": "Storage space in Gulshan-Badda Link Road 3",
    "location": "Gulshan-Badda Link Road 3",
    "price": 16000,
    "units": "750 sqft / Ground floor",
    "sizeSqft": 750,
    "sizeRange": "300-799 sqft",
    "floor": "Ground",
    "propertyType": "Residential (modified)",
    "intendedUse": "Storage",
    "contact": "017 1546 9577",
    "contactName": "Iqbal",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/oSqESW3vcecpDmR76?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgA9CMAcSkL2SqEkpp_sx6RKAc0N5S-_0B0z2OfEh212JtM?e=jMTbsE",
    "photoUrl": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80",
    "deposit": "3 month",
    "ratePerSqft": 21.33,
    "utilities": {
      "gas": "Res Line",
      "electric": "Res",
      "water": "Res"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "No"
    },
    "description": "Storage Residential (modified) space at Gulshan-Badda Link Road 3. Utilities: gas Res Line, electric Res, water Res. Access: 24/7 Yes, truck Yes, exhaust No."
  },
  {
    "id": "registry-42-madani-avenue-solmait",
    "registryNo": 42,
    "brand": "Active",
    "status": "Active",
    "title": "Retail space in Madani Avenue",
    "location": "Madani Avenue, solmait",
    "price": 60000,
    "units": "1800 sqft / Ground floor",
    "sizeSqft": 1800,
    "sizeRange": "1,500-2,499 sqft",
    "floor": "Ground",
    "propertyType": "Commercial",
    "intendedUse": "Retail",
    "contact": "018 1922 1729",
    "contactName": "Bablu",
    "identity": "Owner",
    "lat": null,
    "lng": null,
    "mapLink": "https://maps.app.goo.gl/mkxh9RiLDzfN76t37?g_st=aw",
    "propertyLink": "https://youthactionforbd-my.sharepoint.com/:f:/g/personal/mahadi_livecorps_com/IgBcTIOvhz0aTKeOsysb9LI-AS4OKjIcm3H1fNxZ-brIeO4?e=mcJmO0",
    "photoUrl": "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=80",
    "deposit": "2.5 month",
    "ratePerSqft": 33.33,
    "utilities": {
      "gas": "LPG",
      "electric": "Com",
      "water": "Com"
    },
    "access": {
      "alwaysOpen": "Yes",
      "truck": "Yes",
      "exhaust": "Yes"
    },
    "description": "Retail Commercial space at Madani Avenue, solmait. Utilities: gas LPG, electric Com, water Com. Access: 24/7 Yes, truck Yes, exhaust Yes."
  }
];
